services:
  db:
    ports:
      - "5434:5432"
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=freelahub_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: